import React, { useEffect, useState } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { Button } from '../components/common/Button';
import { Icon } from '../components/common/Icon';
import { useNovel } from '../hooks/useNovel';
import { decodeShareHash } from '../utils/shareLink';
import './Pages.css';
import './ImportShared.css';

// Landing page for links generated by ShareModal. The whole novel travels
// inside the URL's hash fragment (see utils/shareLink.js) — this page just
// decodes it, shows a preview, and adds a read-only copy to the local
// library on confirmation. No network request is made at all.
export const ImportShared = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const { novels, importSharedNovel } = useNovel();

  const [payload, setPayload] = useState(undefined); // undefined = loading, null = invalid
  const [imported, setImported] = useState(null);

  useEffect(() => {
    const decoded = decodeShareHash(location.hash || window.location.hash);
    setPayload(decoded || null);
  }, [location.hash]);

  const alreadyImported = payload
    ? novels.find((n) => n.isShared && n.sourceId === payload.sourceId)
    : null;

  const handleAdd = () => {
    if (!payload) return;
    const novel = importSharedNovel(payload);
    setImported(novel);
  };

  const goToNovel = (novel) => navigate(`/reader/${novel.id}`);

  if (payload === undefined) {
    return (
      <div className="page-loader">
        <div className="loader-spinner"></div>
        <p>กำลังอ่านลิงก์แชร์...</p>
      </div>
    );
  }

  if (payload === null) {
    return (
      <div className="import-shared-page">
        <div className="import-shared-card">
          <Icon name="xCircle" size={48} className="import-shared-icon error" />
          <h1>ลิงก์นี้ใช้ไม่ได้</h1>
          <p>ลิงก์อาจไม่สมบูรณ์ ถูกตัดขาด หรือไม่ใช่ลิงก์แชร์นิยายจาก SECTiON</p>
          <Button variant="primary" onClick={() => navigate('/library')}>
            กลับไปที่คลังนิยาย
          </Button>
        </div>
      </div>
    );
  }

  const { novel, sharedBy } = payload;
  const chapterCount = novel.chapters?.length || 0;
  const target = imported || alreadyImported;

  return (
    <div className="import-shared-page">
      <div className="import-shared-card">
        <Icon name="users" size={40} className="import-shared-icon" />
        <p className="import-shared-eyebrow">คุณได้รับลิงก์แชร์นิยาย</p>
        <h1>{novel.title}</h1>
        <p className="import-shared-meta">
          โดย {sharedBy} • {chapterCount} ตอน
        </p>
        {novel.synopsis && <p className="import-shared-synopsis">{novel.synopsis}</p>}

        <div className="import-shared-notice">
          <Icon name="lock" size={16} />
          <span>คุณจะได้สิทธิ์<strong>อ่านอย่างเดียว</strong> — แก้ไขหรือลบต้นฉบับของผู้เขียนไม่ได้</span>
        </div>

        {target ? (
          <>
            <div className="import-shared-success">
              <Icon name="checkCircle" size={20} />
              <span>
                {imported ? 'เพิ่มเข้าคลังนิยายของคุณแล้ว' : 'นิยายเรื่องนี้อยู่ในคลังของคุณอยู่แล้ว'}
              </span>
            </div>
            <Button variant="primary" fullWidth onClick={() => goToNovel(target)}>
              เริ่มอ่าน
            </Button>
          </>
        ) : (
          <Button variant="primary" fullWidth onClick={handleAdd}>
            เพิ่มเข้าคลังนิยาย (อ่านอย่างเดียว)
          </Button>
        )}

        <button className="import-shared-cancel" onClick={() => navigate('/library')}>
          ไม่ใช่ตอนนี้ กลับไปที่คลังนิยาย
        </button>
      </div>
    </div>
  );
};

export default ImportShared;
